"""Report rendering and redaction."""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from jinja2 import Template

from inflab.security import redact_text

REPORT_TEMPLATE = Template(
    """# {{ name }} Performance Report

## Summary

- Runtime mode: {{ runtime_mode }}
- Framework: {{ framework }} {{ framework_version }}
- Prompt dataset: {{ prompt_dataset }}
- Launch command: `{{ launch_command }}`

## Reproducibility

```json
{{ reproducibility }}
```

## Metrics

- TTFT P50: {{ metrics.get("ttft_p50_ms", 0) }} ms
- TPOT P50: {{ metrics.get("tpot_p50_ms", 0) }} ms
- Throughput: {{ metrics.get("tokens_per_second", 0) }} tokens/s

## Notes

Generated by the MVP report renderer. PDF and DOCX export are represented as artifact interfaces
until the Pandoc/Typst toolchain is installed in the runtime image.
"""
)


def render_markdown_report(
    *,
    name: str,
    runtime_mode: str,
    framework: str,
    framework_version: str,
    prompt_dataset: str,
    launch_command: str,
    reproducibility: dict[str, object],
    metrics: dict[str, float],
) -> str:
    markdown = REPORT_TEMPLATE.render(
        name=name,
        runtime_mode=runtime_mode,
        framework=framework,
        framework_version=framework_version,
        prompt_dataset=prompt_dataset,
        launch_command=launch_command,
        reproducibility=reproducibility,
        metrics=metrics,
    )
    return redact_text(markdown)


def export_report(markdown: str, *, output_format: str) -> bytes:
    if output_format == "markdown":
        return markdown.encode()
    if output_format not in {"pdf", "docx"}:
        raise ValueError("report format must be markdown, pdf, or docx")

    suffix = ".pdf" if output_format == "pdf" else ".docx"
    with tempfile.TemporaryDirectory() as tmpdir:
        input_path = Path(tmpdir) / "report.md"
        output_path = Path(tmpdir) / f"report{suffix}"
        input_path.write_text(markdown)
        command = ["pandoc", str(input_path), "-o", str(output_path)]
        if output_format == "pdf":
            command.extend(["--pdf-engine=typst"])
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=120,
        )
        if completed.returncode != 0:
            message = completed.stderr.strip() or completed.stdout.strip() or "pandoc export failed"
            raise RuntimeError(message)
        return output_path.read_bytes()
